import { Category, MenuItem } from '../types/restaurant';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'starters', name: 'Starters', slug: 'starters', sortOrder: 1, description: 'Crispy, wok-tossed appetizers and sizzlers' },
  { id: 'soups', name: 'Soups', slug: 'soups', sortOrder: 2, description: 'Aromatic, soul-warming broths and slow-simmered Asian soups' },
  { id: 'rolls-crispy', name: 'Rolls & Crispy Snacks', slug: 'rolls-crispy', sortOrder: 3, description: 'Golden hand-rolled spring rolls and crunchy wok delights' },
  { id: 'lollipops', name: 'Lollipops', slug: 'lollipops', sortOrder: 4, description: 'Iconic Indo-Chinese chicken wing lollipops tossed in bold sauces' },
  { id: 'tandoor-special', name: 'Tandoor Special', slug: 'tandoor-special', sortOrder: 5, description: 'Clay-oven infused Asian fusion skewers and charred delights' },
  { id: 'chopsuey', name: 'Chopsuey', slug: 'chopsuey', sortOrder: 6, description: 'Crunchy golden noodles topped with sweet, sour and savoury gravies' },
  { id: 'noodles', name: 'Noodles', slug: 'noodles', sortOrder: 7, description: 'Wok-tossed Hakka, Schezwan, and Malaysian Mee Goreng ribbons' },
  { id: 'ramen', name: 'Ramen', slug: 'ramen', sortOrder: 8, description: 'Rich, comforting Korean and Japanese style broth noodle bowls' },
  { id: 'rice', name: 'Rice', slug: 'rice', sortOrder: 9, description: 'Wok-charred fried rice, triple schezwan and Indonesian Nasi Goreng' },
  { id: 'pot-rice', name: 'Pot Rice', slug: 'pot-rice', sortOrder: 10, description: 'Signature Hot Wok clay-pot layered rice with simmering exotic gravy' },
  { id: 'kepsa', name: 'Kepsa', slug: 'kepsa', sortOrder: 11, description: 'Grand celebratory fusion Asian spiced rice platters with tandoori/crispy chicken' },
  { id: 'gravy', name: 'Gravy', slug: 'gravy', sortOrder: 12, description: 'Velvety Manchurian, Chilli, and Black Bean gravies' },
  { id: 'chicken-gravy', name: 'Chicken Gravy/Fusion Special', slug: 'chicken-gravy', sortOrder: 13, description: 'Specialty Malaysian Sambal, Thai Curry, and Korean Glazed gravies' },
  { id: 'chef-special', name: 'Chef Special', slug: 'chef-special', sortOrder: 14, description: 'Handcrafted signature masterworks designed by our executive chef' },
  { id: 'veg', name: 'Veg Delicacies', slug: 'veg', sortOrder: 15, description: 'Dedicated pure vegetarian Asian specialties, paneer and exotic mushrooms' },
  { id: 'non-veg', name: 'Non-Veg Specialties', slug: 'non-veg', sortOrder: 16, description: 'Tender chicken, lamb, and seafood delicacies' }
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // Starters
  {
    id: 'starter-1',
    name: 'Hot Wok Dragon Chicken',
    description: 'Crisp fried chicken strips tossed with crunchy cashews, dried red chillies, capsicum, and house honey-chilli glaze.',
    categoryId: 'starters',
    categoryName: 'Starters',
    isVeg: false,
    priceType: 'single',
    price: 280,
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 1
  },
  {
    id: 'starter-2',
    name: 'Korean Gochujang Sticky Wings',
    description: 'Double-fried crispy chicken wings glazed in a sweet, smoky and fermented Korean chili glaze with sesame.',
    categoryId: 'starters',
    categoryName: 'Starters',
    isVeg: false,
    priceType: 'single',
    price: 310,
    image: 'https://images.unsplash.com/photo-1527477378378-f7eb54f7a26f?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Korean',
    spiceLevel: 2,
    sortOrder: 2
  },
  {
    id: 'starter-3',
    name: 'Paneer Chilli Basil Wok',
    description: 'Fresh cottage cheese cubes wok-seared with fresh Thai basil, bell peppers, garlic cloves, and dark soy.',
    categoryId: 'starters',
    categoryName: 'Starters',
    isVeg: true,
    priceType: 'single',
    price: 250,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Thai',
    spiceLevel: 1,
    sortOrder: 3
  },
  {
    id: 'starter-4',
    name: 'Crispy Malaysian Satay Chicken',
    description: 'Tender chicken skewers marinated with lemongrass and turmeric, flame-grilled and served with rich peanut dip.',
    categoryId: 'starters',
    categoryName: 'Starters',
    isVeg: false,
    priceType: 'single',
    price: 290,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Malaysian',
    spiceLevel: 1,
    sortOrder: 4
  },

  // Soups
  {
    id: 'soup-1',
    name: 'Classic Chicken Manchow Soup',
    description: 'Thick, spicy broth infused with ginger, garlic, cilantro, shredded chicken and crowned with crisp fried noodles.',
    categoryId: 'soups',
    categoryName: 'Soups',
    isVeg: false,
    priceType: 'single',
    price: 180,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 10
  },
  {
    id: 'soup-2',
    name: 'Thai Tom Yum Seafood / Chicken Soup',
    description: 'Fragrant spicy & sour lemongrass broth infused with kaffir lime leaves, galangal, mushrooms and red chillies.',
    categoryId: 'soups',
    categoryName: 'Soups',
    isVeg: false,
    priceType: 'single',
    price: 210,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Thai',
    spiceLevel: 3,
    sortOrder: 11
  },
  {
    id: 'soup-3',
    name: 'Exotic Veg Sweet Corn Soup',
    description: 'Velvety creamy golden corn broth simmered with tender baby corn, carrots, and spring onions.',
    categoryId: 'soups',
    categoryName: 'Soups',
    isVeg: true,
    priceType: 'single',
    price: 160,
    image: 'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 0,
    sortOrder: 12
  },

  // Rolls & Crispy Snacks
  {
    id: 'roll-1',
    name: 'Chicken Threaded Spring Rolls (6 Pcs)',
    description: 'Spiced chicken marinated with sesame oil, wrapped in delicate crunchy noodle threads and fried to golden perfection.',
    categoryId: 'rolls-crispy',
    categoryName: 'Rolls & Crispy Snacks',
    isVeg: false,
    priceType: 'single',
    price: 270,
    image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 20
  },
  {
    id: 'roll-2',
    name: 'Golden Veg Spring Rolls with Sweet Chilli',
    description: 'Handcrafted wafer rolls stuffed with crunchy shredded cabbage, carrots, glass noodles, and Chinese five-spice.',
    categoryId: 'rolls-crispy',
    categoryName: 'Rolls & Crispy Snacks',
    isVeg: true,
    priceType: 'single',
    price: 220,
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 21
  },

  // Lollipops
  {
    id: 'loll-1',
    name: 'Hot Wok Special Chicken Lollipop (6 Pcs)',
    description: 'Crispy fried chicken winglets served with our legendary in-house spicy Schezwan dipping sauce.',
    categoryId: 'lollipops',
    categoryName: 'Lollipops',
    isVeg: false,
    priceType: 'portion',
    price: 260,
    halfPrice: 170, // 3 pcs
    fullPrice: 280, // 6 pcs
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 30
  },
  {
    id: 'loll-2',
    name: 'Chicken Lollipop Masala / Schezwan Tossed',
    description: 'Crisp chicken winglets tossed in fiery garlic, ginger, chopped chillies, and savory soy sauce.',
    categoryId: 'lollipops',
    categoryName: 'Lollipops',
    isVeg: false,
    priceType: 'portion',
    price: 290,
    halfPrice: 190,
    fullPrice: 310,
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 3,
    sortOrder: 31
  },

  // Tandoor Special
  {
    id: 'tandoor-1',
    name: 'Asian Charred Tandoori Chicken Tikka',
    description: 'Juicy boneless chicken thighs marinated with lemongrass, ginger paste, kashmiri chili, and grilled in the tandoor.',
    categoryId: 'tandoor-special',
    categoryName: 'Tandoor Special',
    isVeg: false,
    priceType: 'portion',
    price: 320,
    halfPrice: 210,
    fullPrice: 340,
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 40
  },
  {
    id: 'tandoor-2',
    name: 'Malai Cheese Paneer Asian Skewers',
    description: 'Melt-in-mouth paneer cubes steeped in rich cream, cardamom, mild wasabi and grilled to golden perfection.',
    categoryId: 'tandoor-special',
    categoryName: 'Tandoor Special',
    isVeg: true,
    priceType: 'single',
    price: 290,
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 1,
    sortOrder: 41
  },

  // Chopsuey
  {
    id: 'chopsuey-1',
    name: 'American Chicken Chopsuey',
    description: 'Bed of golden crispy noodles crowned with sweet & sour shredded chicken gravy, vegetables and a fried egg.',
    categoryId: 'chopsuey',
    categoryName: 'Chopsuey',
    isVeg: false,
    priceType: 'single',
    price: 270,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 50
  },
  {
    id: 'chopsuey-2',
    name: 'Chinese Spicy Veg Chopsuey',
    description: 'Crisp noodles tossed with spicy garlic soya gravy, baby corn, mushrooms, bell peppers, and scallions.',
    categoryId: 'chopsuey',
    categoryName: 'Chopsuey',
    isVeg: true,
    priceType: 'single',
    price: 230,
    image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 51
  },

  // Noodles
  {
    id: 'noodles-1',
    name: 'Hot Wok Signature Chicken Hakka Noodles',
    description: 'Smoky wok-tossed thin egg noodles with julienned chicken, shredded cabbage, carrots, bell peppers, and light soy.',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    isVeg: false,
    priceType: 'portion',
    price: 250,
    halfPrice: 170,
    fullPrice: 260,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 60
  },
  {
    id: 'noodles-2',
    name: 'Malaysian Mee Goreng Mamak (Chicken / Prawn)',
    description: 'Street-style spicy Malaysian stir-fried noodles with chicken, fried tofu, bean sprouts, crushed peanuts, and calamansi lime.',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    isVeg: false,
    priceType: 'single',
    price: 290,
    image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Malaysian',
    spiceLevel: 2,
    sortOrder: 61
  },
  {
    id: 'noodles-3',
    name: 'Classic Thai Pad Thai Noodles',
    description: 'Flat rice noodles stir-fried with tamarind sauce, palm sugar, tofu, crushed peanuts, bean sprouts, and lime wedge.',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    isVeg: true,
    priceType: 'single',
    price: 280,
    image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Thai',
    spiceLevel: 1,
    sortOrder: 62
  },

  // Ramen
  {
    id: 'ramen-1',
    name: 'Spicy Korean Shin Ramyun Bowl',
    description: 'Springy ramen noodles in an intense umami kimchi broth, topped with grilled chicken, soft egg, nori sheet, and scallions.',
    categoryId: 'ramen',
    categoryName: 'Ramen',
    isVeg: false,
    priceType: 'single',
    price: 340,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Korean',
    spiceLevel: 3,
    sortOrder: 70
  },
  {
    id: 'ramen-2',
    name: 'Malaysian Coconut Curry Laksa Ramen',
    description: 'Rich and aromatic coconut curry broth with egg noodles, tofu puffs, seasonal greens, boiled egg, and fresh coriander.',
    categoryId: 'ramen',
    categoryName: 'Ramen',
    isVeg: true,
    priceType: 'single',
    price: 320,
    image: 'https://images.unsplash.com/photo-1591814468924-caf88d1232e1?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Malaysian',
    spiceLevel: 2,
    sortOrder: 71
  },

  // Rice
  {
    id: 'rice-1',
    name: 'Chicken Triple Schezwan Fried Rice',
    description: 'Legendary Mumbai Indo-Chinese feast: wok-tossed Schezwan rice and noodles served with spicy chicken gravy and crispy noodles.',
    categoryId: 'rice',
    categoryName: 'Rice',
    isVeg: false,
    priceType: 'portion',
    price: 310,
    halfPrice: 200,
    fullPrice: 320,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 80
  },
  {
    id: 'rice-2',
    name: 'Indonesian Nasi Goreng with Chicken Satay',
    description: 'Aromatic fried rice seasoned with kecap manis sweet soy, shallots, garlic, topped with fried egg and grilled satay skewers.',
    categoryId: 'rice',
    categoryName: 'Rice',
    isVeg: false,
    priceType: 'single',
    price: 330,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Malaysian',
    spiceLevel: 1,
    sortOrder: 81
  },
  {
    id: 'rice-3',
    name: 'Exotic Burnt Garlic Veg Fried Rice',
    description: 'Fluffy long-grain rice infused with wok-roasted golden garlic flakes, finely chopped broccoli, and garden vegetables.',
    categoryId: 'rice',
    categoryName: 'Rice',
    isVeg: true,
    priceType: 'portion',
    price: 240,
    halfPrice: 150,
    fullPrice: 240,
    image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 0,
    sortOrder: 82
  },

  // Pot Rice
  {
    id: 'pot-rice-1',
    name: 'Signature Hot Wok Chicken Pot Rice',
    description: 'Steaming fragrant rice layered in a hot clay pot, smothered with rich brown garlic chicken gravy, mushrooms, and greens.',
    categoryId: 'pot-rice',
    categoryName: 'Pot Rice',
    isVeg: false,
    priceType: 'portion',
    price: 340,
    halfPrice: 230,
    fullPrice: 350,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 90
  },
  {
    id: 'pot-rice-2',
    name: 'Clay Pot Paneer & Exotic Veggie Pot Rice',
    description: 'Fragrant steamed rice topped with thick sizzling Schezwan oyster-style vegan gravy, paneer, and baby corn.',
    categoryId: 'pot-rice',
    categoryName: 'Pot Rice',
    isVeg: true,
    priceType: 'portion',
    price: 300,
    halfPrice: 190,
    fullPrice: 310,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 1,
    sortOrder: 91
  },

  // Kepsa
  {
    id: 'kepsa-1',
    name: 'Hot Wok Special Chicken Kepsa Rice (Grand Platter)',
    description: 'Our Mumbra crowd favorite: colossal platter of spiced saffron-infused Asian rice, topped with crispy chicken tikka, rich spicy gravy, boiled eggs, and dry fruit garnish.',
    categoryId: 'kepsa',
    categoryName: 'Kepsa',
    isVeg: false,
    priceType: 'portion',
    price: 590,
    halfPrice: 340,
    fullPrice: 620,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 100
  },
  {
    id: 'kepsa-2',
    name: 'Chicken Tandoori Kepsa with Schezwan Glaze',
    description: 'Spiced aromatic rice smothered with rich Schezwan-infused gravy and adorned with full bone-in charcoal tandoori chicken.',
    categoryId: 'kepsa',
    categoryName: 'Kepsa',
    isVeg: false,
    priceType: 'portion',
    price: 640,
    halfPrice: 380,
    fullPrice: 660,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 3,
    sortOrder: 101
  },

  // Gravy
  {
    id: 'gravy-1',
    name: 'Classic Chicken Manchurian Gravy',
    description: 'Minced chicken dumplings simmered in a dark soy, ginger, coriander, and scallion gravy. Perfect with fried rice.',
    categoryId: 'gravy',
    categoryName: 'Gravy',
    isVeg: false,
    priceType: 'portion',
    price: 270,
    halfPrice: 170,
    fullPrice: 280,
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 110
  },
  {
    id: 'gravy-2',
    name: 'Veg Ball Manchurian in Dark Soya Gravy',
    description: 'Crispy minced vegetable balls immersed in garlic, ginger, and green chilli rich Manchurian broth.',
    categoryId: 'gravy',
    categoryName: 'Gravy',
    isVeg: true,
    priceType: 'portion',
    price: 230,
    halfPrice: 150,
    fullPrice: 240,
    image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 111
  },

  // Chicken Gravy / Fusion Special
  {
    id: 'chick-gravy-1',
    name: 'Malaysian Sambal Chicken Gravy',
    description: 'Slow-simmered chicken chunks in an authentic Malaysian sambal paste with dried shrimp essence, lemongrass, and tamarind.',
    categoryId: 'chicken-gravy',
    categoryName: 'Chicken Gravy/Fusion Special',
    isVeg: false,
    priceType: 'single',
    price: 320,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Malaysian',
    spiceLevel: 3,
    sortOrder: 120
  },
  {
    id: 'chick-gravy-2',
    name: 'Authentic Thai Green Chicken Curry',
    description: 'Tender chicken simmered in rich coconut milk with Thai green herbs, kaffir lime, bamboo shoots, and basil.',
    categoryId: 'chicken-gravy',
    categoryName: 'Chicken Gravy/Fusion Special',
    isVeg: false,
    priceType: 'single',
    price: 340,
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Thai',
    spiceLevel: 2,
    sortOrder: 121
  },

  // Chef Special
  {
    id: 'chef-1',
    name: 'Chef Imperial Sizzling Chicken Platter',
    description: 'Boneless chicken marinated with Korean spices, served on a sizzling hot iron plate over butter-tossed noodles with house glaze.',
    categoryId: 'chef-special',
    categoryName: 'Chef Special',
    isVeg: false,
    priceType: 'single',
    price: 390,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 130
  },
  {
    id: 'chef-2',
    name: 'Crispy Honey Chilli Lotus Stem & Water Chestnuts',
    description: 'Thin lotus root crisps and crunchy water chestnuts tossed with crushed sesame, scallions, and mountain wildflower honey.',
    categoryId: 'chef-special',
    categoryName: 'Chef Special',
    isVeg: true,
    priceType: 'single',
    price: 310,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 131
  }
];

export const INITIAL_REVIEWS = [
  {
    id: 'rev-1',
    name: 'Farhan Shaikh',
    rating: 5,
    comment: 'The Chicken Kepsa and Dragon Chicken here are out of this world! Perfect rich flavors and genuine Thai/Chinese fusion right in Mumbra.',
    dishRecommended: 'Hot Wok Special Chicken Kepsa Rice',
    approved: true,
    createdAt: '2026-09-15T19:30:00.000Z'
  },
  {
    id: 'rev-2',
    name: 'Ayesha Khan',
    rating: 5,
    comment: 'Exceptional ambiance, prompt service, and the Korean Gochujang Wings were super crispy and authentic. Definitely our family weekend spot now.',
    dishRecommended: 'Korean Gochujang Sticky Wings',
    approved: true,
    createdAt: '2026-09-18T20:45:00.000Z'
  },
  {
    id: 'rev-3',
    name: 'Rohan Deshmukh',
    rating: 5,
    comment: 'Hot Wok Chicken Pot Rice was sizzling and mouth-watering. Best Asian food experience around Kausar Baug!',
    dishRecommended: 'Hot Wok Chicken Pot Rice',
    approved: true,
    createdAt: '2026-09-20T21:10:00.000Z'
  }
];
