import { Category, MenuItem } from '../types/restaurant';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'starters', name: 'Starters', slug: 'starters', sortOrder: 1, description: 'Crispy, wok-tossed appetizers and sizzlers' },
  { id: 'soups', name: 'Soups', slug: 'soups', sortOrder: 2, description: 'Aromatic, soul-warming broths and slow-simmered Asian soups' },
  { id: 'chopsuey', name: 'Chopsuey', slug: 'chopsuey', sortOrder: 3, description: 'Crunchy golden noodles topped with sweet, sour and savoury gravies' },
  { id: 'noodles', name: 'Noodles', slug: 'noodles', sortOrder: 4, description: 'Wok-tossed Hakka, Schezwan, and Malaysian ribbons' },
  { id: 'rice', name: 'Rice', slug: 'rice', sortOrder: 5, description: 'Wok-charred fried rice, triple schezwan and specialty Asian rice' },
  { id: 'pot-rice', name: 'Pot Rice', slug: 'pot-rice', sortOrder: 6, description: 'Clay-pot layered rice with simmering exotic gravy' },
  { id: 'kepsa', name: 'Kepsa', slug: 'kepsa', sortOrder: 7, description: 'Celebratory fusion Asian spiced rice platters with tandoori and crispy toppings' },
  { id: 'gravy', name: 'Gravy', slug: 'gravy', sortOrder: 8, description: 'Velvety Manchurian, Chilli, and garlic gravies' },
  { id: 'chicken-starters', name: 'Chicken Starters / Chef Specials', slug: 'chicken-starters', sortOrder: 9, description: 'Chef specialty chicken appetizers and sizzling wok creations' },
  { id: 'tandoor-special', name: 'Tandoor Special', slug: 'tandoor-special', sortOrder: 10, description: 'Clay-oven infused Asian fusion skewers and charred delights' },
  { id: 'rolls-crispy', name: 'Rolls & Crispy Snacks', slug: 'rolls-crispy', sortOrder: 11, description: 'Golden hand-rolled spring rolls and crunchy snacks' },
  { id: 'lollipops', name: 'Lollipops', slug: 'lollipops', sortOrder: 12, description: 'Chicken wing lollipops served dry or tossed in signature sauces' },
  { id: 'chinese-fusion-special', name: 'Chinese/Fusion Special sections', slug: 'chinese-fusion-special', sortOrder: 13, description: 'Specialty Malaysian Sambal, Thai Curry, and Korean Glazed gravies' },
  { id: 'ramen', name: 'Ramen', slug: 'ramen', sortOrder: 14, description: 'Korean and Asian broth noodle bowls' }
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // ==========================================
  // 1. STARTERS (Veg Appetizers & Crispy Delights)
  // ==========================================
  {
    id: 'starter-veg-crispy',
    name: 'Veg Crispy',
    category: 'Starters',
    categoryId: 'starters',
    categoryName: 'Starters',
    subcategory: 'Veg Starters',
    isVeg: true,
    priceType: 'portion',
    price: 240,
    halfPrice: 150,
    fullPrice: 240,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 101
  },
  {
    id: 'starter-paneer-crispy',
    name: 'Paneer Crispy',
    category: 'Starters',
    categoryId: 'starters',
    categoryName: 'Starters',
    subcategory: 'Veg Starters',
    isVeg: true,
    priceType: 'portion',
    price: 270,
    halfPrice: 170,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 102
  },
  {
    id: 'starter-veg-manchurian-dry',
    name: 'Veg Manchurian Dry',
    category: 'Starters',
    categoryId: 'starters',
    categoryName: 'Starters',
    subcategory: 'Veg Starters',
    isVeg: true,
    priceType: 'portion',
    price: 220,
    halfPrice: 140,
    fullPrice: 220,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 103
  },
  {
    id: 'starter-paneer-manchurian-dry',
    name: 'Paneer Manchurian Dry',
    category: 'Starters',
    categoryId: 'starters',
    categoryName: 'Starters',
    subcategory: 'Veg Starters',
    isVeg: true,
    priceType: 'portion',
    price: 260,
    halfPrice: 160,
    fullPrice: 260,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 104
  },
  {
    id: 'starter-paneer-chilli-dry',
    name: 'Paneer Chilli Dry',
    category: 'Starters',
    categoryId: 'starters',
    categoryName: 'Starters',
    subcategory: 'Veg Starters',
    isVeg: true,
    priceType: 'portion',
    price: 270,
    halfPrice: 170,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 105
  },
  {
    id: 'starter-veg-65-dry',
    name: 'Veg 65 Dry',
    category: 'Starters',
    categoryId: 'starters',
    categoryName: 'Starters',
    subcategory: 'Veg Starters',
    isVeg: true,
    priceType: 'portion',
    price: 230,
    halfPrice: 150,
    fullPrice: 230,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 106
  },
  {
    id: 'starter-paneer-65-dry',
    name: 'Paneer 65 Dry',
    category: 'Starters',
    categoryId: 'starters',
    categoryName: 'Starters',
    subcategory: 'Veg Starters',
    isVeg: true,
    priceType: 'portion',
    price: 270,
    halfPrice: 170,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 107
  },
  {
    id: 'starter-veg-schezwan-dry',
    name: 'Veg Schezwan Dry',
    category: 'Starters',
    categoryId: 'starters',
    categoryName: 'Starters',
    subcategory: 'Veg Starters',
    isVeg: true,
    priceType: 'portion',
    price: 230,
    halfPrice: 150,
    fullPrice: 230,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 108
  },
  {
    id: 'starter-crispy-corn',
    name: 'Crispy Corn Salt & Pepper',
    category: 'Starters',
    categoryId: 'starters',
    categoryName: 'Starters',
    subcategory: 'Veg Starters',
    isVeg: true,
    priceType: 'single',
    price: 220,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 109
  },
  {
    id: 'starter-mushroom-chilli-dry',
    name: 'Mushroom Chilli Dry',
    category: 'Starters',
    categoryId: 'starters',
    categoryName: 'Starters',
    subcategory: 'Veg Starters',
    isVeg: true,
    priceType: 'single',
    price: 250,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 110
  },
  {
    id: 'starter-honey-chilli-potato',
    name: 'Honey Chilli Potato',
    category: 'Starters',
    categoryId: 'starters',
    categoryName: 'Starters',
    subcategory: 'Veg Starters',
    isVeg: true,
    priceType: 'single',
    price: 220,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 111
  },

  // ==========================================
  // 2. SOUPS (Veg & Non-Veg Soups)
  // ==========================================
  {
    id: 'soup-veg-manchow',
    name: 'Veg Manchow Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Veg Soups',
    isVeg: true,
    priceType: 'single',
    price: 140,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 201
  },
  {
    id: 'soup-chicken-manchow',
    name: 'Chicken Manchow Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Non-Veg Soups',
    isVeg: false,
    priceType: 'single',
    price: 170,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 202
  },
  {
    id: 'soup-veg-hot-sour',
    name: 'Veg Hot & Sour Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Veg Soups',
    isVeg: true,
    priceType: 'single',
    price: 140,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 203
  },
  {
    id: 'soup-chicken-hot-sour',
    name: 'Chicken Hot & Sour Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Non-Veg Soups',
    isVeg: false,
    priceType: 'single',
    price: 170,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 204
  },
  {
    id: 'soup-veg-sweet-corn',
    name: 'Veg Sweet Corn Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Veg Soups',
    isVeg: true,
    priceType: 'single',
    price: 140,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 0,
    sortOrder: 205
  },
  {
    id: 'soup-chicken-sweet-corn',
    name: 'Chicken Sweet Corn Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Non-Veg Soups',
    isVeg: false,
    priceType: 'single',
    price: 170,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 0,
    sortOrder: 206
  },
  {
    id: 'soup-veg-clear',
    name: 'Veg Clear Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Veg Soups',
    isVeg: true,
    priceType: 'single',
    price: 130,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 0,
    sortOrder: 207
  },
  {
    id: 'soup-chicken-clear',
    name: 'Chicken Clear Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Non-Veg Soups',
    isVeg: false,
    priceType: 'single',
    price: 160,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 0,
    sortOrder: 208
  },
  {
    id: 'soup-veg-burnt-garlic',
    name: 'Veg Burnt Garlic Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Veg Soups',
    isVeg: true,
    priceType: 'single',
    price: 150,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 209
  },
  {
    id: 'soup-chicken-burnt-garlic',
    name: 'Chicken Burnt Garlic Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Non-Veg Soups',
    isVeg: false,
    priceType: 'single',
    price: 180,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 210
  },
  {
    id: 'soup-royal-hot-wok-veg',
    name: 'Royal Hot Wok Veg Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Veg Soups',
    isVeg: true,
    priceType: 'single',
    price: 160,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 211
  },
  {
    id: 'soup-royal-hot-wok-chicken',
    name: 'Royal Hot Wok Chicken Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Non-Veg Soups',
    isVeg: false,
    priceType: 'single',
    price: 200,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 212
  },
  {
    id: 'soup-chicken-lung-fung',
    name: 'Chicken Lung Fung Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Non-Veg Soups',
    isVeg: false,
    priceType: 'single',
    price: 190,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 213
  },
  {
    id: 'soup-veg-tom-yum',
    name: 'Veg Tom Yum Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Veg Soups',
    isVeg: true,
    priceType: 'single',
    price: 160,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Thai',
    spiceLevel: 3,
    sortOrder: 214
  },
  {
    id: 'soup-chicken-tom-yum',
    name: 'Chicken Tom Yum Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Non-Veg Soups',
    isVeg: false,
    priceType: 'single',
    price: 210,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Thai',
    spiceLevel: 3,
    sortOrder: 215
  },
  {
    id: 'soup-veg-lemon-coriander',
    name: 'Veg Lemon Coriander Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Veg Soups',
    isVeg: true,
    priceType: 'single',
    price: 140,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 216
  },
  {
    id: 'soup-chicken-lemon-coriander',
    name: 'Chicken Lemon Coriander Soup',
    category: 'Soups',
    categoryId: 'soups',
    categoryName: 'Soups',
    subcategory: 'Non-Veg Soups',
    isVeg: false,
    priceType: 'single',
    price: 170,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 217
  },

  // ==========================================
  // 3. CHOPSUEY (Veg & Chicken Chopsuey)
  // ==========================================
  {
    id: 'chopsuey-veg-american',
    name: 'Veg American Chopsuey',
    category: 'Chopsuey',
    categoryId: 'chopsuey',
    categoryName: 'Chopsuey',
    subcategory: 'Veg Chopsuey',
    isVeg: true,
    priceType: 'single',
    price: 220,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 301
  },
  {
    id: 'chopsuey-chicken-american',
    name: 'Chicken American Chopsuey',
    category: 'Chopsuey',
    categoryId: 'chopsuey',
    categoryName: 'Chopsuey',
    subcategory: 'Non-Veg Chopsuey',
    isVeg: false,
    priceType: 'single',
    price: 260,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 302
  },
  {
    id: 'chopsuey-veg-chinese',
    name: 'Veg Chinese Chopsuey',
    category: 'Chopsuey',
    categoryId: 'chopsuey',
    categoryName: 'Chopsuey',
    subcategory: 'Veg Chopsuey',
    isVeg: true,
    priceType: 'single',
    price: 220,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 303
  },
  {
    id: 'chopsuey-chicken-chinese',
    name: 'Chicken Chinese Chopsuey',
    category: 'Chopsuey',
    categoryId: 'chopsuey',
    categoryName: 'Chopsuey',
    subcategory: 'Non-Veg Chopsuey',
    isVeg: false,
    priceType: 'single',
    price: 260,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 304
  },
  {
    id: 'chopsuey-hot-wok-special-veg',
    name: 'Hot Wok Special Veg Chopsuey',
    category: 'Chopsuey',
    categoryId: 'chopsuey',
    categoryName: 'Chopsuey',
    subcategory: 'Veg Chopsuey',
    isVeg: true,
    priceType: 'single',
    price: 250,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 305
  },
  {
    id: 'chopsuey-hot-wok-special-chicken',
    name: 'Hot Wok Special Chicken Chopsuey',
    category: 'Chopsuey',
    categoryId: 'chopsuey',
    categoryName: 'Chopsuey',
    subcategory: 'Non-Veg Chopsuey',
    isVeg: false,
    priceType: 'single',
    price: 290,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 306
  },
  {
    id: 'chopsuey-veg-schezwan',
    name: 'Veg Schezwan Chopsuey',
    category: 'Chopsuey',
    categoryId: 'chopsuey',
    categoryName: 'Chopsuey',
    subcategory: 'Veg Chopsuey',
    isVeg: true,
    priceType: 'single',
    price: 230,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 307
  },
  {
    id: 'chopsuey-chicken-schezwan',
    name: 'Chicken Schezwan Chopsuey',
    category: 'Chopsuey',
    categoryId: 'chopsuey',
    categoryName: 'Chopsuey',
    subcategory: 'Non-Veg Chopsuey',
    isVeg: false,
    priceType: 'single',
    price: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 308
  },

  // ==========================================
  // 4. NOODLES (Veg & Non-Veg with Half & Full)
  // ==========================================
  {
    id: 'noodle-veg-hakka',
    name: 'Veg Hakka Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Veg Noodles',
    isVeg: true,
    priceType: 'portion',
    price: 220,
    halfPrice: 140,
    fullPrice: 220,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 401
  },
  {
    id: 'noodle-chicken-hakka',
    name: 'Chicken Hakka Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Non-Veg Noodles',
    isVeg: false,
    priceType: 'portion',
    price: 250,
    halfPrice: 160,
    fullPrice: 250,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 402
  },
  {
    id: 'noodle-veg-schezwan',
    name: 'Veg Schezwan Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Veg Noodles',
    isVeg: true,
    priceType: 'portion',
    price: 230,
    halfPrice: 150,
    fullPrice: 230,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 403
  },
  {
    id: 'noodle-chicken-schezwan',
    name: 'Chicken Schezwan Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Non-Veg Noodles',
    isVeg: false,
    priceType: 'portion',
    price: 260,
    halfPrice: 170,
    fullPrice: 260,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 404
  },
  {
    id: 'noodle-veg-singapore',
    name: 'Veg Singapore Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Veg Noodles',
    isVeg: true,
    priceType: 'portion',
    price: 240,
    halfPrice: 160,
    fullPrice: 240,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 405
  },
  {
    id: 'noodle-chicken-singapore',
    name: 'Chicken Singapore Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Non-Veg Noodles',
    isVeg: false,
    priceType: 'portion',
    price: 270,
    halfPrice: 180,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 406
  },
  {
    id: 'noodle-veg-hong-kong',
    name: 'Veg Hong Kong Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Veg Noodles',
    isVeg: true,
    priceType: 'portion',
    price: 240,
    halfPrice: 160,
    fullPrice: 240,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 407
  },
  {
    id: 'noodle-chicken-hong-kong',
    name: 'Chicken Hong Kong Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Non-Veg Noodles',
    isVeg: false,
    priceType: 'portion',
    price: 270,
    halfPrice: 180,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 408
  },
  {
    id: 'noodle-veg-burnt-garlic',
    name: 'Veg Burnt Garlic Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Veg Noodles',
    isVeg: true,
    priceType: 'portion',
    price: 240,
    halfPrice: 160,
    fullPrice: 240,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 409
  },
  {
    id: 'noodle-chicken-burnt-garlic',
    name: 'Chicken Burnt Garlic Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Non-Veg Noodles',
    isVeg: false,
    priceType: 'portion',
    price: 270,
    halfPrice: 180,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 410
  },
  {
    id: 'noodle-veg-chilli-garlic',
    name: 'Veg Chilli Garlic Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Veg Noodles',
    isVeg: true,
    priceType: 'portion',
    price: 230,
    halfPrice: 150,
    fullPrice: 230,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 411
  },
  {
    id: 'noodle-chicken-chilli-garlic',
    name: 'Chicken Chilli Garlic Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Non-Veg Noodles',
    isVeg: false,
    priceType: 'portion',
    price: 260,
    halfPrice: 170,
    fullPrice: 260,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 412
  },
  {
    id: 'noodle-veg-triple-schezwan',
    name: 'Veg Triple Schezwan Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Veg Noodles',
    isVeg: true,
    priceType: 'portion',
    price: 290,
    halfPrice: 190,
    fullPrice: 290,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 413
  },
  {
    id: 'noodle-chicken-triple-schezwan',
    name: 'Chicken Triple Schezwan Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Non-Veg Noodles',
    isVeg: false,
    priceType: 'portion',
    price: 330,
    halfPrice: 220,
    fullPrice: 330,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 414
  },
  {
    id: 'noodle-malaysian-mee-goreng',
    name: 'Malaysian Mee Goreng',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Asian Specialty Noodles',
    isVeg: false,
    priceType: 'single',
    price: 290,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Malaysian',
    spiceLevel: 2,
    sortOrder: 415
  },
  {
    id: 'noodle-pad-thai-veg',
    name: 'Veg Pad Thai Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Thai Specialty Noodles',
    isVeg: true,
    priceType: 'single',
    price: 260,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Thai',
    spiceLevel: 1,
    sortOrder: 416
  },
  {
    id: 'noodle-pad-thai-chicken',
    name: 'Chicken Pad Thai Noodles',
    category: 'Noodles',
    categoryId: 'noodles',
    categoryName: 'Noodles',
    subcategory: 'Thai Specialty Noodles',
    isVeg: false,
    priceType: 'single',
    price: 300,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Thai',
    spiceLevel: 1,
    sortOrder: 417
  },

  // ==========================================
  // 5. RICE (Veg & Non-Veg with Half & Full)
  // ==========================================
  {
    id: 'rice-veg-fried',
    name: 'Veg Fried Rice',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Veg Rice',
    isVeg: true,
    priceType: 'portion',
    price: 220,
    halfPrice: 140,
    fullPrice: 220,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 0,
    sortOrder: 501
  },
  {
    id: 'rice-chicken-fried',
    name: 'Chicken Fried Rice',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Non-Veg Rice',
    isVeg: false,
    priceType: 'portion',
    price: 250,
    halfPrice: 160,
    fullPrice: 250,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 0,
    sortOrder: 502
  },
  {
    id: 'rice-veg-schezwan',
    name: 'Veg Schezwan Fried Rice',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Veg Rice',
    isVeg: true,
    priceType: 'portion',
    price: 230,
    halfPrice: 150,
    fullPrice: 230,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 503
  },
  {
    id: 'rice-chicken-schezwan',
    name: 'Chicken Schezwan Fried Rice',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Non-Veg Rice',
    isVeg: false,
    priceType: 'portion',
    price: 260,
    halfPrice: 170,
    fullPrice: 260,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 504
  },
  {
    id: 'rice-veg-triple-schezwan',
    name: 'Veg Triple Schezwan Fried Rice',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Veg Rice',
    isVeg: true,
    priceType: 'portion',
    price: 290,
    halfPrice: 190,
    fullPrice: 290,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 505
  },
  {
    id: 'rice-chicken-triple-schezwan',
    name: 'Chicken Triple Schezwan Fried Rice',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Non-Veg Rice',
    isVeg: false,
    priceType: 'portion',
    price: 330,
    halfPrice: 220,
    fullPrice: 330,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 506
  },
  {
    id: 'rice-veg-manchurian',
    name: 'Veg Manchurian Fried Rice',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Veg Rice',
    isVeg: true,
    priceType: 'portion',
    price: 270,
    halfPrice: 180,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 507
  },
  {
    id: 'rice-chicken-manchurian',
    name: 'Chicken Manchurian Fried Rice',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Non-Veg Rice',
    isVeg: false,
    priceType: 'portion',
    price: 310,
    halfPrice: 210,
    fullPrice: 310,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 508
  },
  {
    id: 'rice-veg-burnt-garlic',
    name: 'Veg Burnt Garlic Fried Rice',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Veg Rice',
    isVeg: true,
    priceType: 'portion',
    price: 240,
    halfPrice: 160,
    fullPrice: 240,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 0,
    sortOrder: 509
  },
  {
    id: 'rice-chicken-burnt-garlic',
    name: 'Chicken Burnt Garlic Fried Rice',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Non-Veg Rice',
    isVeg: false,
    priceType: 'portion',
    price: 270,
    halfPrice: 180,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 0,
    sortOrder: 510
  },
  {
    id: 'rice-veg-singapore',
    name: 'Veg Singapore Fried Rice',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Veg Rice',
    isVeg: true,
    priceType: 'portion',
    price: 240,
    halfPrice: 160,
    fullPrice: 240,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 511
  },
  {
    id: 'rice-chicken-singapore',
    name: 'Chicken Singapore Fried Rice',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Non-Veg Rice',
    isVeg: false,
    priceType: 'portion',
    price: 270,
    halfPrice: 180,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 512
  },
  {
    id: 'rice-veg-combination',
    name: 'Veg Combination Fried Rice (Rice & Noodles)',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Veg Rice',
    isVeg: true,
    priceType: 'portion',
    price: 240,
    halfPrice: 160,
    fullPrice: 240,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 513
  },
  {
    id: 'rice-chicken-combination',
    name: 'Chicken Combination Fried Rice (Rice & Noodles)',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Non-Veg Rice',
    isVeg: false,
    priceType: 'portion',
    price: 270,
    halfPrice: 180,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 514
  },
  {
    id: 'rice-nasi-goreng-chicken',
    name: 'Indonesian Nasi Goreng',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Asian Specialty Rice',
    isVeg: false,
    priceType: 'single',
    price: 320,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Malaysian',
    spiceLevel: 1,
    sortOrder: 515
  },
  {
    id: 'rice-hot-wok-special-chicken',
    name: 'Hot Wok Special Chicken Fried Rice',
    category: 'Rice',
    categoryId: 'rice',
    categoryName: 'Rice',
    subcategory: 'Specialty Rice',
    isVeg: false,
    priceType: 'single',
    price: 320,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 516
  },

  // ==========================================
  // 6. POT RICE (Claypot Layered Specialties)
  // ==========================================
  {
    id: 'pot-rice-veg',
    name: 'Veg Pot Rice',
    category: 'Pot Rice',
    categoryId: 'pot-rice',
    categoryName: 'Pot Rice',
    subcategory: 'Veg Pot Rice',
    isVeg: true,
    priceType: 'portion',
    price: 300,
    halfPrice: 190,
    fullPrice: 300,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 1,
    sortOrder: 601
  },
  {
    id: 'pot-rice-paneer',
    name: 'Paneer Pot Rice',
    category: 'Pot Rice',
    categoryId: 'pot-rice',
    categoryName: 'Pot Rice',
    subcategory: 'Veg Pot Rice',
    isVeg: true,
    priceType: 'portion',
    price: 320,
    halfPrice: 210,
    fullPrice: 320,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 1,
    sortOrder: 602
  },
  {
    id: 'pot-rice-mushroom-babycorn',
    name: 'Mushroom & Baby Corn Pot Rice',
    category: 'Pot Rice',
    categoryId: 'pot-rice',
    categoryName: 'Pot Rice',
    subcategory: 'Veg Pot Rice',
    isVeg: true,
    priceType: 'portion',
    price: 310,
    halfPrice: 200,
    fullPrice: 310,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 1,
    sortOrder: 603
  },
  {
    id: 'pot-rice-chicken',
    name: 'Chicken Pot Rice',
    category: 'Pot Rice',
    categoryId: 'pot-rice',
    categoryName: 'Pot Rice',
    subcategory: 'Non-Veg Pot Rice',
    isVeg: false,
    priceType: 'portion',
    price: 350,
    halfPrice: 230,
    fullPrice: 350,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 604
  },
  {
    id: 'pot-rice-hot-wok-special-chicken',
    name: 'Hot Wok Special Chicken Pot Rice',
    category: 'Pot Rice',
    categoryId: 'pot-rice',
    categoryName: 'Pot Rice',
    subcategory: 'Non-Veg Pot Rice',
    isVeg: false,
    priceType: 'portion',
    price: 380,
    halfPrice: 250,
    fullPrice: 380,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 605
  },
  {
    id: 'pot-rice-schezwan-chicken',
    name: 'Schezwan Chicken Pot Rice',
    category: 'Pot Rice',
    categoryId: 'pot-rice',
    categoryName: 'Pot Rice',
    subcategory: 'Non-Veg Pot Rice',
    isVeg: false,
    priceType: 'portion',
    price: 360,
    halfPrice: 240,
    fullPrice: 360,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 3,
    sortOrder: 606
  },

  // ==========================================
  // 7. KEPSA (Grand Celebratory Fusion Rice)
  // ==========================================
  {
    id: 'kepsa-chicken-tikka',
    name: 'Chicken Tikka Kepsa',
    category: 'Kepsa',
    categoryId: 'kepsa',
    categoryName: 'Kepsa',
    subcategory: 'Kepsa Platters',
    isVeg: false,
    priceType: 'portion',
    price: 620,
    halfPrice: 350,
    fullPrice: 620,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 701
  },
  {
    id: 'kepsa-chicken-tandoori',
    name: 'Chicken Tandoori Kepsa',
    category: 'Kepsa',
    categoryId: 'kepsa',
    categoryName: 'Kepsa',
    subcategory: 'Kepsa Platters',
    isVeg: false,
    priceType: 'portion',
    price: 660,
    halfPrice: 380,
    fullPrice: 660,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 702
  },
  {
    id: 'kepsa-hot-wok-special',
    name: 'Hot Wok Special Chicken Kepsa',
    category: 'Kepsa',
    categoryId: 'kepsa',
    categoryName: 'Kepsa',
    subcategory: 'Kepsa Platters',
    isVeg: false,
    priceType: 'portion',
    price: 690,
    halfPrice: 390,
    fullPrice: 690,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 703
  },
  {
    id: 'kepsa-chicken-crispy',
    name: 'Chicken Crispy Kepsa',
    category: 'Kepsa',
    categoryId: 'kepsa',
    categoryName: 'Kepsa',
    subcategory: 'Kepsa Platters',
    isVeg: false,
    priceType: 'portion',
    price: 640,
    halfPrice: 360,
    fullPrice: 640,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 704
  },
  {
    id: 'kepsa-chicken-schezwan',
    name: 'Chicken Schezwan Kepsa',
    category: 'Kepsa',
    categoryId: 'kepsa',
    categoryName: 'Kepsa',
    subcategory: 'Kepsa Platters',
    isVeg: false,
    priceType: 'portion',
    price: 630,
    halfPrice: 360,
    fullPrice: 630,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 3,
    sortOrder: 705
  },
  {
    id: 'kepsa-chicken-lollipop',
    name: 'Chicken Lollipop Kepsa',
    category: 'Kepsa',
    categoryId: 'kepsa',
    categoryName: 'Kepsa',
    subcategory: 'Kepsa Platters',
    isVeg: false,
    priceType: 'portion',
    price: 650,
    halfPrice: 370,
    fullPrice: 650,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 706
  },
  {
    id: 'kepsa-veg-paneer',
    name: 'Veg Paneer Kepsa',
    category: 'Kepsa',
    categoryId: 'kepsa',
    categoryName: 'Kepsa',
    subcategory: 'Veg Kepsa Platters',
    isVeg: true,
    priceType: 'portion',
    price: 540,
    halfPrice: 320,
    fullPrice: 540,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 1,
    sortOrder: 707
  },
  {
    id: 'kepsa-chicken-seekh',
    name: 'Chicken Seekh Kepsa',
    category: 'Kepsa',
    categoryId: 'kepsa',
    categoryName: 'Kepsa',
    subcategory: 'Kepsa Platters',
    isVeg: false,
    priceType: 'portion',
    price: 630,
    halfPrice: 360,
    fullPrice: 630,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 708
  },

  // ==========================================
  // 8. GRAVY (Veg Gravies with Half & Full)
  // ==========================================
  {
    id: 'gravy-veg-manchurian',
    name: 'Veg Manchurian Gravy',
    category: 'Gravy',
    categoryId: 'gravy',
    categoryName: 'Gravy',
    subcategory: 'Veg Gravy',
    isVeg: true,
    priceType: 'portion',
    price: 230,
    halfPrice: 150,
    fullPrice: 230,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 801
  },
  {
    id: 'gravy-paneer-manchurian',
    name: 'Paneer Manchurian Gravy',
    category: 'Gravy',
    categoryId: 'gravy',
    categoryName: 'Gravy',
    subcategory: 'Veg Gravy',
    isVeg: true,
    priceType: 'portion',
    price: 260,
    halfPrice: 170,
    fullPrice: 260,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 802
  },
  {
    id: 'gravy-veg-chilli',
    name: 'Veg Chilli Gravy',
    category: 'Gravy',
    categoryId: 'gravy',
    categoryName: 'Gravy',
    subcategory: 'Veg Gravy',
    isVeg: true,
    priceType: 'portion',
    price: 230,
    halfPrice: 150,
    fullPrice: 230,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 803
  },
  {
    id: 'gravy-paneer-chilli',
    name: 'Paneer Chilli Gravy',
    category: 'Gravy',
    categoryId: 'gravy',
    categoryName: 'Gravy',
    subcategory: 'Veg Gravy',
    isVeg: true,
    priceType: 'portion',
    price: 260,
    halfPrice: 170,
    fullPrice: 260,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 804
  },
  {
    id: 'gravy-veg-hot-garlic',
    name: 'Veg Hot Garlic Gravy',
    category: 'Gravy',
    categoryId: 'gravy',
    categoryName: 'Gravy',
    subcategory: 'Veg Gravy',
    isVeg: true,
    priceType: 'portion',
    price: 240,
    halfPrice: 160,
    fullPrice: 240,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 805
  },
  {
    id: 'gravy-veg-schezwan',
    name: 'Veg Schezwan Gravy',
    category: 'Gravy',
    categoryId: 'gravy',
    categoryName: 'Gravy',
    subcategory: 'Veg Gravy',
    isVeg: true,
    priceType: 'portion',
    price: 230,
    halfPrice: 150,
    fullPrice: 230,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 806
  },

  // ==========================================
  // 9. CHICKEN STARTERS / CHEF SPECIALS
  // ==========================================
  {
    id: 'starter-chicken-crispy',
    name: 'Chicken Crispy',
    category: 'Chicken Starters / Chef Specials',
    categoryId: 'chicken-starters',
    categoryName: 'Chicken Starters / Chef Specials',
    subcategory: 'Chicken Starters',
    isVeg: false,
    priceType: 'portion',
    price: 280,
    halfPrice: 180,
    fullPrice: 280,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 901
  },
  {
    id: 'starter-chicken-dragon',
    name: 'Chicken Dragon',
    category: 'Chicken Starters / Chef Specials',
    categoryId: 'chicken-starters',
    categoryName: 'Chicken Starters / Chef Specials',
    subcategory: 'Chef Specials',
    isVeg: false,
    priceType: 'single',
    price: 290,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 902
  },
  {
    id: 'starter-chicken-manchurian-dry',
    name: 'Chicken Manchurian Dry',
    category: 'Chicken Starters / Chef Specials',
    categoryId: 'chicken-starters',
    categoryName: 'Chicken Starters / Chef Specials',
    subcategory: 'Chicken Starters',
    isVeg: false,
    priceType: 'portion',
    price: 270,
    halfPrice: 170,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1527477378378-f7eb54f7a26f?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 903
  },
  {
    id: 'starter-chicken-chilli-dry',
    name: 'Chicken Chilli Dry',
    category: 'Chicken Starters / Chef Specials',
    categoryId: 'chicken-starters',
    categoryName: 'Chicken Starters / Chef Specials',
    subcategory: 'Chicken Starters',
    isVeg: false,
    priceType: 'portion',
    price: 270,
    halfPrice: 170,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1527477378378-f7eb54f7a26f?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 904
  },
  {
    id: 'starter-chicken-65-dry',
    name: 'Chicken 65 Dry',
    category: 'Chicken Starters / Chef Specials',
    categoryId: 'chicken-starters',
    categoryName: 'Chicken Starters / Chef Specials',
    subcategory: 'Chicken Starters',
    isVeg: false,
    priceType: 'portion',
    price: 270,
    halfPrice: 170,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 905
  },
  {
    id: 'starter-chicken-schezwan-dry',
    name: 'Chicken Schezwan Dry',
    category: 'Chicken Starters / Chef Specials',
    categoryId: 'chicken-starters',
    categoryName: 'Chicken Starters / Chef Specials',
    subcategory: 'Chicken Starters',
    isVeg: false,
    priceType: 'portion',
    price: 270,
    halfPrice: 170,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 906
  },
  {
    id: 'starter-chicken-hot-garlic',
    name: 'Chicken Hot Garlic',
    category: 'Chicken Starters / Chef Specials',
    categoryId: 'chicken-starters',
    categoryName: 'Chicken Starters / Chef Specials',
    subcategory: 'Chef Specials',
    isVeg: false,
    priceType: 'single',
    price: 280,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 907
  },
  {
    id: 'starter-chicken-black-pepper',
    name: 'Chicken Black Pepper',
    category: 'Chicken Starters / Chef Specials',
    categoryId: 'chicken-starters',
    categoryName: 'Chicken Starters / Chef Specials',
    subcategory: 'Chef Specials',
    isVeg: false,
    priceType: 'single',
    price: 290,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 908
  },
  {
    id: 'starter-chicken-kung-pao',
    name: 'Chicken Kung Pao',
    category: 'Chicken Starters / Chef Specials',
    categoryId: 'chicken-starters',
    categoryName: 'Chicken Starters / Chef Specials',
    subcategory: 'Chef Specials',
    isVeg: false,
    priceType: 'single',
    price: 310,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1527477378378-f7eb54f7a26f?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 909
  },
  {
    id: 'starter-chicken-salt-pepper',
    name: 'Chicken Salt & Pepper',
    category: 'Chicken Starters / Chef Specials',
    categoryId: 'chicken-starters',
    categoryName: 'Chicken Starters / Chef Specials',
    subcategory: 'Chef Specials',
    isVeg: false,
    priceType: 'single',
    price: 280,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 910
  },
  {
    id: 'starter-korean-gochujang-wings',
    name: 'Korean Gochujang Sticky Wings',
    category: 'Chicken Starters / Chef Specials',
    categoryId: 'chicken-starters',
    categoryName: 'Chicken Starters / Chef Specials',
    subcategory: 'Korean Specials',
    isVeg: false,
    priceType: 'single',
    price: 310,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1527477378378-f7eb54f7a26f?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Korean',
    spiceLevel: 2,
    sortOrder: 911
  },
  {
    id: 'starter-chicken-teriyaki',
    name: 'Chicken Teriyaki',
    category: 'Chicken Starters / Chef Specials',
    categoryId: 'chicken-starters',
    categoryName: 'Chicken Starters / Chef Specials',
    subcategory: 'Chef Specials',
    isVeg: false,
    priceType: 'single',
    price: 300,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 1,
    sortOrder: 912
  },
  {
    id: 'starter-hot-wok-special-chicken',
    name: 'Hot Wok Special Chicken Starter',
    category: 'Chicken Starters / Chef Specials',
    categoryId: 'chicken-starters',
    categoryName: 'Chicken Starters / Chef Specials',
    subcategory: 'Chef Specials',
    isVeg: false,
    priceType: 'single',
    price: 330,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 913
  },

  // ==========================================
  // 10. TANDOOR SPECIAL (Clay-Oven Asian Fusion)
  // ==========================================
  {
    id: 'tandoor-chicken-tandoori',
    name: 'Tandoori Chicken',
    category: 'Tandoor Special',
    categoryId: 'tandoor-special',
    categoryName: 'Tandoor Special',
    subcategory: 'Chicken Tandoor',
    isVeg: false,
    priceType: 'portion',
    price: 410,
    halfPrice: 220,
    fullPrice: 410,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 1001
  },
  {
    id: 'tandoor-chicken-tikka',
    name: 'Chicken Tikka',
    category: 'Tandoor Special',
    categoryId: 'tandoor-special',
    categoryName: 'Tandoor Special',
    subcategory: 'Chicken Tandoor',
    isVeg: false,
    priceType: 'portion',
    price: 340,
    halfPrice: 200,
    fullPrice: 340,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 1002
  },
  {
    id: 'tandoor-chicken-pahadi-tikka',
    name: 'Chicken Pahadi Tikka',
    category: 'Tandoor Special',
    categoryId: 'tandoor-special',
    categoryName: 'Tandoor Special',
    subcategory: 'Chicken Tandoor',
    isVeg: false,
    priceType: 'portion',
    price: 350,
    halfPrice: 210,
    fullPrice: 350,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 1003
  },
  {
    id: 'tandoor-chicken-malai-tikka',
    name: 'Chicken Malai Tikka',
    category: 'Tandoor Special',
    categoryId: 'tandoor-special',
    categoryName: 'Tandoor Special',
    subcategory: 'Chicken Tandoor',
    isVeg: false,
    priceType: 'portion',
    price: 360,
    halfPrice: 220,
    fullPrice: 360,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 1,
    sortOrder: 1004
  },
  {
    id: 'tandoor-chicken-banjara-tikka',
    name: 'Chicken Banjara Tikka',
    category: 'Tandoor Special',
    categoryId: 'tandoor-special',
    categoryName: 'Tandoor Special',
    subcategory: 'Chicken Tandoor',
    isVeg: false,
    priceType: 'portion',
    price: 350,
    halfPrice: 210,
    fullPrice: 350,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 1005
  },
  {
    id: 'tandoor-chicken-achari-tikka',
    name: 'Chicken Achari Tikka',
    category: 'Tandoor Special',
    categoryId: 'tandoor-special',
    categoryName: 'Tandoor Special',
    subcategory: 'Chicken Tandoor',
    isVeg: false,
    priceType: 'portion',
    price: 350,
    halfPrice: 210,
    fullPrice: 350,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 1006
  },
  {
    id: 'tandoor-chicken-seekh-kebab',
    name: 'Chicken Seekh Kebab',
    category: 'Tandoor Special',
    categoryId: 'tandoor-special',
    categoryName: 'Tandoor Special',
    subcategory: 'Chicken Tandoor',
    isVeg: false,
    priceType: 'single',
    price: 290,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 1007
  },
  {
    id: 'tandoor-paneer-tikka',
    name: 'Paneer Tikka',
    category: 'Tandoor Special',
    categoryId: 'tandoor-special',
    categoryName: 'Tandoor Special',
    subcategory: 'Veg Tandoor',
    isVeg: true,
    priceType: 'single',
    price: 280,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 1,
    sortOrder: 1008
  },
  {
    id: 'tandoor-paneer-malai-tikka',
    name: 'Paneer Malai Tikka',
    category: 'Tandoor Special',
    categoryId: 'tandoor-special',
    categoryName: 'Tandoor Special',
    subcategory: 'Veg Tandoor',
    isVeg: true,
    priceType: 'single',
    price: 300,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 1,
    sortOrder: 1009
  },

  // ==========================================
  // 11. ROLLS & CRISPY SNACKS
  // ==========================================
  {
    id: 'roll-chicken-spring',
    name: 'Chicken Spring Roll',
    category: 'Rolls & Crispy Snacks',
    categoryId: 'rolls-crispy',
    categoryName: 'Rolls & Crispy Snacks',
    subcategory: 'Rolls',
    isVeg: false,
    priceType: 'single',
    price: 250,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 1101
  },
  {
    id: 'roll-veg-spring',
    name: 'Veg Spring Roll',
    category: 'Rolls & Crispy Snacks',
    categoryId: 'rolls-crispy',
    categoryName: 'Rolls & Crispy Snacks',
    subcategory: 'Rolls',
    isVeg: true,
    priceType: 'single',
    price: 200,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 1102
  },
  {
    id: 'roll-chicken-thread',
    name: 'Chicken Thread Roll',
    category: 'Rolls & Crispy Snacks',
    categoryId: 'rolls-crispy',
    categoryName: 'Rolls & Crispy Snacks',
    subcategory: 'Rolls',
    isVeg: false,
    priceType: 'single',
    price: 280,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 1103
  },
  {
    id: 'roll-chicken-cheese',
    name: 'Chicken Cheese Roll',
    category: 'Rolls & Crispy Snacks',
    categoryId: 'rolls-crispy',
    categoryName: 'Rolls & Crispy Snacks',
    subcategory: 'Rolls',
    isVeg: false,
    priceType: 'single',
    price: 290,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 1,
    sortOrder: 1104
  },
  {
    id: 'roll-chicken-crispy',
    name: 'Chicken Crispy Roll',
    category: 'Rolls & Crispy Snacks',
    categoryId: 'rolls-crispy',
    categoryName: 'Rolls & Crispy Snacks',
    subcategory: 'Rolls',
    isVeg: false,
    priceType: 'single',
    price: 260,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 1105
  },
  {
    id: 'snack-crispy-wonton-veg',
    name: 'Crispy Veg Wonton',
    category: 'Rolls & Crispy Snacks',
    categoryId: 'rolls-crispy',
    categoryName: 'Rolls & Crispy Snacks',
    subcategory: 'Crispy Snacks',
    isVeg: true,
    priceType: 'single',
    price: 190,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 1106
  },
  {
    id: 'snack-crispy-wonton-chicken',
    name: 'Crispy Chicken Wonton',
    category: 'Rolls & Crispy Snacks',
    categoryId: 'rolls-crispy',
    categoryName: 'Rolls & Crispy Snacks',
    subcategory: 'Crispy Snacks',
    isVeg: false,
    priceType: 'single',
    price: 230,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 1107
  },

  // ==========================================
  // 12. LOLLIPOPS (Iconic Chicken Lollipops)
  // ==========================================
  {
    id: 'lollipop-chicken-dry',
    name: 'Chicken Lollipop Dry',
    category: 'Lollipops',
    categoryId: 'lollipops',
    categoryName: 'Lollipops',
    subcategory: 'Chicken Lollipops',
    isVeg: false,
    priceType: 'portion',
    price: 280,
    halfPrice: 170,
    fullPrice: 280,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 1201
  },
  {
    id: 'lollipop-chicken-masala',
    name: 'Chicken Lollipop Masala Tossed',
    category: 'Lollipops',
    categoryId: 'lollipops',
    categoryName: 'Lollipops',
    subcategory: 'Chicken Lollipops',
    isVeg: false,
    priceType: 'portion',
    price: 310,
    halfPrice: 190,
    fullPrice: 310,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Chinese',
    spiceLevel: 3,
    sortOrder: 1202
  },
  {
    id: 'lollipop-chicken-schezwan',
    name: 'Chicken Lollipop Schezwan',
    category: 'Lollipops',
    categoryId: 'lollipops',
    categoryName: 'Lollipops',
    subcategory: 'Chicken Lollipops',
    isVeg: false,
    priceType: 'portion',
    price: 310,
    halfPrice: 190,
    fullPrice: 310,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 3,
    sortOrder: 1203
  },
  {
    id: 'lollipop-chicken-gravy',
    name: 'Chicken Lollipop Gravy',
    category: 'Lollipops',
    categoryId: 'lollipops',
    categoryName: 'Lollipops',
    subcategory: 'Chicken Lollipops',
    isVeg: false,
    priceType: 'portion',
    price: 310,
    halfPrice: 190,
    fullPrice: 310,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 1204
  },
  {
    id: 'lollipop-chicken-oil-fry',
    name: 'Chicken Lollipop Oil Fry',
    category: 'Lollipops',
    categoryId: 'lollipops',
    categoryName: 'Lollipops',
    subcategory: 'Chicken Lollipops',
    isVeg: false,
    priceType: 'portion',
    price: 280,
    halfPrice: 170,
    fullPrice: 280,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 1205
  },

  // ==========================================
  // 13. CHINESE/FUSION SPECIAL SECTIONS
  // ==========================================
  {
    id: 'gravy-chicken-manchurian',
    name: 'Chicken Manchurian Gravy',
    category: 'Chinese/Fusion Special sections',
    categoryId: 'chinese-fusion-special',
    categoryName: 'Chinese/Fusion Special sections',
    subcategory: 'Specialty Chicken Gravies',
    isVeg: false,
    priceType: 'portion',
    price: 270,
    halfPrice: 170,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 1301
  },
  {
    id: 'gravy-chicken-chilli',
    name: 'Chicken Chilli Gravy',
    category: 'Chinese/Fusion Special sections',
    categoryId: 'chinese-fusion-special',
    categoryName: 'Chinese/Fusion Special sections',
    subcategory: 'Specialty Chicken Gravies',
    isVeg: false,
    priceType: 'portion',
    price: 270,
    halfPrice: 170,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 1302
  },
  {
    id: 'gravy-chicken-schezwan',
    name: 'Chicken Schezwan Gravy',
    category: 'Chinese/Fusion Special sections',
    categoryId: 'chinese-fusion-special',
    categoryName: 'Chinese/Fusion Special sections',
    subcategory: 'Specialty Chicken Gravies',
    isVeg: false,
    priceType: 'portion',
    price: 270,
    halfPrice: 170,
    fullPrice: 270,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 1303
  },
  {
    id: 'gravy-chicken-hot-garlic',
    name: 'Chicken Hot Garlic Gravy',
    category: 'Chinese/Fusion Special sections',
    categoryId: 'chinese-fusion-special',
    categoryName: 'Chinese/Fusion Special sections',
    subcategory: 'Specialty Chicken Gravies',
    isVeg: false,
    priceType: 'portion',
    price: 280,
    halfPrice: 180,
    fullPrice: 280,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 2,
    sortOrder: 1304
  },
  {
    id: 'gravy-chicken-black-bean',
    name: 'Chicken Black Bean Gravy',
    category: 'Chinese/Fusion Special sections',
    categoryId: 'chinese-fusion-special',
    categoryName: 'Chinese/Fusion Special sections',
    subcategory: 'Specialty Chicken Gravies',
    isVeg: false,
    priceType: 'single',
    price: 310,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Chinese',
    spiceLevel: 1,
    sortOrder: 1305
  },
  {
    id: 'gravy-malaysian-sambal-chicken',
    name: 'Malaysian Sambal Chicken Gravy',
    category: 'Chinese/Fusion Special sections',
    categoryId: 'chinese-fusion-special',
    categoryName: 'Chinese/Fusion Special sections',
    subcategory: 'Malaysian Special',
    isVeg: false,
    priceType: 'single',
    price: 320,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Malaysian',
    spiceLevel: 3,
    sortOrder: 1306
  },
  {
    id: 'gravy-thai-green-chicken-curry',
    name: 'Thai Green Chicken Curry',
    category: 'Chinese/Fusion Special sections',
    categoryId: 'chinese-fusion-special',
    categoryName: 'Chinese/Fusion Special sections',
    subcategory: 'Thai Special',
    isVeg: false,
    priceType: 'single',
    price: 340,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Thai',
    spiceLevel: 2,
    sortOrder: 1307
  },
  {
    id: 'gravy-thai-red-chicken-curry',
    name: 'Thai Red Chicken Curry',
    category: 'Chinese/Fusion Special sections',
    categoryId: 'chinese-fusion-special',
    categoryName: 'Chinese/Fusion Special sections',
    subcategory: 'Thai Special',
    isVeg: false,
    priceType: 'single',
    price: 340,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Thai',
    spiceLevel: 2,
    sortOrder: 1308
  },
  {
    id: 'special-hot-wok-sizzling-chicken',
    name: 'Hot Wok Sizzling Chicken Platter',
    category: 'Chinese/Fusion Special sections',
    categoryId: 'chinese-fusion-special',
    categoryName: 'Chinese/Fusion Special sections',
    subcategory: 'Chef Special Sizzlers',
    isVeg: false,
    priceType: 'single',
    price: 390,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 1309
  },
  {
    id: 'special-chef-paneer-sizzler',
    name: 'Chef Special Paneer Sizzler',
    category: 'Chinese/Fusion Special sections',
    categoryId: 'chinese-fusion-special',
    categoryName: 'Chinese/Fusion Special sections',
    subcategory: 'Chef Special Sizzlers',
    isVeg: true,
    priceType: 'single',
    price: 350,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Fusion',
    spiceLevel: 1,
    sortOrder: 1310
  },

  // ==========================================
  // 14. RAMEN (Korean & Asian Broth Bowls)
  // ==========================================
  {
    id: 'ramen-veg-kimchi',
    name: 'Veg Kimchi Ramen Bowl',
    category: 'Ramen',
    categoryId: 'ramen',
    categoryName: 'Ramen',
    subcategory: 'Ramen Bowls',
    isVeg: true,
    priceType: 'single',
    price: 280,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Korean',
    spiceLevel: 2,
    sortOrder: 1401
  },
  {
    id: 'ramen-spicy-korean-shin',
    name: 'Spicy Korean Shin Ramyun Bowl',
    category: 'Ramen',
    categoryId: 'ramen',
    categoryName: 'Ramen',
    subcategory: 'Ramen Bowls',
    isVeg: false,
    priceType: 'single',
    price: 340,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Korean',
    spiceLevel: 3,
    sortOrder: 1402
  },
  {
    id: 'ramen-hot-wok-chicken',
    name: 'Hot Wok Asian Chicken Ramen',
    category: 'Ramen',
    categoryId: 'ramen',
    categoryName: 'Ramen',
    subcategory: 'Ramen Bowls',
    isVeg: false,
    priceType: 'single',
    price: 350,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    cuisine: 'Fusion',
    spiceLevel: 2,
    sortOrder: 1403
  },
  {
    id: 'ramen-malaysian-curry-laksa',
    name: 'Malaysian Coconut Curry Laksa Ramen',
    category: 'Ramen',
    categoryId: 'ramen',
    categoryName: 'Ramen',
    subcategory: 'Ramen Bowls',
    isVeg: true,
    priceType: 'single',
    price: 330,
    description: 'Available at Hot Wok Asian Cuisine.',
    image: 'https://images.unsplash.com/photo-1591814468924-caf88d1232e1?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    cuisine: 'Malaysian',
    spiceLevel: 2,
    sortOrder: 1404
  }
];

export const INITIAL_REVIEWS = [
  {
    id: 'rev-1',
    name: 'Farhan Shaikh',
    rating: 5,
    comment: 'The Chicken Kepsa and Dragon Chicken here are out of this world! Perfect rich flavors and genuine Asian wok cooking right in Mumbra.',
    dishRecommended: 'Hot Wok Special Chicken Kepsa',
    approved: true,
    createdAt: '2026-09-15T19:30:00.000Z'
  },
  {
    id: 'rev-2',
    name: 'Ayesha Khan',
    rating: 5,
    comment: 'Prompt delivery, great packaging, and the Korean Gochujang Wings were super crispy and authentic. Definitely our family weekend spot now.',
    dishRecommended: 'Korean Gochujang Sticky Wings',
    approved: true,
    createdAt: '2026-09-18T20:45:00.000Z'
  },
  {
    id: 'rev-3',
    name: 'Rohan Deshmukh',
    rating: 5,
    comment: 'Hot Wok Chicken Pot Rice was sizzling and mouth-watering. Best Asian food experience around Kausar Baug!',
    dishRecommended: 'Hot Wok Special Chicken Pot Rice',
    approved: true,
    createdAt: '2026-09-20T21:10:00.000Z'
  }
];
